#include "src/game.hpp"

#include "src/world.cpp"
#include "src/items.cpp"
#include "src/cows.cpp"
#include "src/sheep.cpp"
#include "src/spiders.cpp"
#include "src/crafting.cpp"
#include "src/input.cpp"
#include "src/actions.cpp"
#include "src/admin.cpp"
#include "src/save.cpp"
#include "src/network.cpp"
#include "src/render.cpp"
#include "src/main_loop.cpp"
